name = "net"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.16"
module_path = "github.com/wetware/casm/testground/plans/net"
fresh_gomod = true
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/wetware/casm/testground/plans/net"
fresh_gomod = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "boot"
instances = { min = 2, max = 100, default = 5 }

    [testcases.params]
    seed = { type = "int", desc = "PRNG seed", default = 0 }
    timeout = { type = "int", desc = "in seconds", default = 60 }

# Add more testcases here...
# [[testcases]]
# name = "another"
# instances = { min = 1, max = 1, default = 1 }
#   [testcase.params]
#   param1 = { type = "int", desc = "an integer", unit = "units", default = 3 }
